# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  #config.vm.synced_folder '.', '/vagrant', type: 'nfs'
  config.vm.synced_folder '.', '/vagrant'

  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "virtualbox-debian-11.2.0"
    virtualbox.vm.box = "file://../builds/debian-11.2.0-amd64-virtualbox.box"
    #virtualbox.vm.network :private_network, ip: "172.16.3.27"

    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      #v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      #v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "shell", inline: "echo Hello, World"
  end

end
